[package]
name = "mem_editor"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = {version = "0.61.1", features = [
    "Win32_Foundation",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_Threading",
]}